channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.1.2
- pip:
  - mlflow==2.15.0
  - cloudpickle==2.2.1
  - packaging==24.1
  - pathlib==1.0.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
name: mlflow-env
